### ISSUE TITLE
Percentages for "by industry" for each candidate percentages are incorrect

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#93] opened 2020-09-07 07:19 UTC
The percentages are showing 8000% (as an example) when viewing the detailed candidate card for each candidate.

**Comment by robertgz** [comment] 2020-09-26 20:14
This issue is a duplicate of item 4 in #102, and was fixed by #112. 
Closing issue.

**Closed by robertgz** 2020-09-26 20:14 UTC
Labels: bug, good first issue
